# Course Assignment: Deep Learning and NLP
## Project Title: Sentiment Analysis of Movie Reviews using LSTM Model
**Submitted by:** [Your Name]  
**Date:*09* June 2026


### Importing Deep Learning Libraries

In [ ]:
# Import neural network tools from keras
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

print("Deep learning tools loaded successfully!")


Deep learning tools loaded successfully!


### : Preparing Text Data (Movie Reviews)

In [ ]:
# Sample dataset of 6 movie reviews
reviews = [
    "This movie was amazing and fantastic",
    "I loved the story and great acting",
    "Beautiful masterpiece completely enjoyed it",
    "Worst movie ever very boring story",
    "Waste of time and terrible acting",
    "I hated this film it was awful"
]

# Labels: 1 = Positive, 0 = Negative
labels = np.array([1, 1, 1, 0, 0, 0])

print("Sample movie reviews dataset is ready!")


Sample movie reviews dataset is ready!


### Text Preprocessing and Word Tokenization

In [ ]:
# 1. Convert words into unique numbers
my_tokenizer = Tokenizer(num_words=100)
my_tokenizer.fit_on_texts(reviews)
sequences = my_tokenizer.texts_to_sequences(reviews)

# 2. Make all review lengths equal (Padding)
padded_reviews = pad_sequences(sequences, maxlen=6)

print("Processed text data into numbers:")
print(padded_reviews)


Processed text data into numbers:
[[ 2  3  4  9  1 10]
 [11 12  6  1 13  7]
 [ 0 14 15 16 17  8]
 [18  3 19 20 21  6]
 [22 23 24  1 25  7]
 [26  2 27  8  4 28]]


###  Building and Training the LSTM Neural Network

In [ ]:
# Create a blank sequential network model
my_lstm_model = Sequential()

# Add layers as required by the assignment
my_lstm_model.add(Embedding(input_dim=100, output_dim=8, input_length=6))
my_lstm_model.add(LSTM(units=8))
my_lstm_model.add(Dense(units=1, activation='sigmoid')) # Output layer for binary classification

# Compile the model
my_lstm_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model for 10 epochs
print("Starting training loop...")
my_lstm_model.fit(padded_reviews, labels, epochs=100, verbose=1)
print("LSTM model training completed successfully!")


Starting training loop...
Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3333 - loss: 0.6938
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.3333 - loss: 0.6935
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6932
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6929
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.6925
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5000 - loss: 0.6922
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8333 - loss: 0.6918
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8333 - loss: 0.6914
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8333 - loss: 0.6911
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.6906
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.6902
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

### Model Prediction on a New Review

In [ ]:
# Provide a new review to test the model
new_review = ["The film was fantastic and great"]

# Preprocess the new review exactly like before
new_seq = my_tokenizer.texts_to_sequences(new_review)
new_padded = pad_sequences(new_seq, maxlen=6)

# Make prediction
prediction_score = my_lstm_model.predict(new_padded)

# Print final readable result based on threshold
if prediction_score > 0.5:
    print(f"Review: '{new_review}' -> Prediction: POSITIVE REVIEW")
else:
    print(f"Review: '{new_review}' -> Prediction: NEGATIVE REVIEW")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step
Review: '['The film was fantastic and great']' -> Prediction: POSITIVE REVIEW
